package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSecretScannerFindsTokenWithoutExposingValue(t *testing.T) {
	secret := "ghp_" + strings.Repeat("A", 36)
	findings := scanSecretContent("example.txt", []byte("token="+secret+"\n"))
	if len(findings) != 1 {
		t.Fatalf("expected one finding, got %#v", findings)
	}
	finding := findings[0]
	if finding.RuleID != "SECRET-GITHUB-TOKEN" || finding.Path != "example.txt" || finding.Line != 1 {
		t.Fatalf("unexpected finding: %#v", finding)
	}
	if strings.Contains(finding.Fingerprint, secret) || len(finding.Fingerprint) != 64 {
		t.Fatalf("finding fingerprint is not redacted SHA-256 evidence: %#v", finding)
	}
}

func TestSecretScannerFindsPrivateKeyBlock(t *testing.T) {
	begin := "-----BEGIN " + "PRIVATE KEY-----"
	end := "-----END " + "PRIVATE KEY-----"
	value := begin + "\n" + strings.Repeat("A", 64) + "\n" + end
	findings := scanSecretContent("key.pem", []byte(value))
	if len(findings) != 1 || findings[0].RuleID != "SECRET-PRIVATE-KEY" {
		t.Fatalf("expected private-key finding, got %#v", findings)
	}
}

func TestSecretAllowlistIsPathAndFingerprintScoped(t *testing.T) {
	secret := []byte("sk_" + "live_" + strings.Repeat("B", 24))
	fp := secretFingerprint("SECRET-STRIPE-LIVE-KEY", secret)
	allowlist := SecretAllowlist{SchemaVersion: 1, Entries: []SecretAllowlistEntry{{
		RuleID: "SECRET-STRIPE-LIVE-KEY", Path: "fixture.txt", Fingerprint: fp, Reason: "synthetic fixture",
	}}}
	index, err := indexSecretAllowlist(allowlist)
	if err != nil {
		t.Fatal(err)
	}
	if !index[secretAllowlistKey("SECRET-STRIPE-LIVE-KEY", "fixture.txt", fp)] {
		t.Fatal("expected exact allowlist key")
	}
	if index[secretAllowlistKey("SECRET-STRIPE-LIVE-KEY", "other.txt", fp)] {
		t.Fatal("allowlist must not apply to another path")
	}
}

func TestSecretAllowlistRejectsNonCanonicalPathAndBadFingerprint(t *testing.T) {
	for _, entry := range []SecretAllowlistEntry{
		{RuleID: "SECRET-GITHUB-TOKEN", Path: "../outside", Fingerprint: strings.Repeat("a", 64), Reason: "bad path"},
		{RuleID: "SECRET-GITHUB-TOKEN", Path: "safe.txt", Fingerprint: "not-a-sha", Reason: "bad fp"},
	} {
		if _, err := indexSecretAllowlist(SecretAllowlist{SchemaVersion: 1, Entries: []SecretAllowlistEntry{entry}}); err == nil {
			t.Fatalf("expected allowlist rejection for %#v", entry)
		}
	}
}

func TestSecretScannerSkipsDeletedBinaryGeneratedAndSymlink(t *testing.T) {
	root := t.TempDir()
	allowlist := filepath.Join(root, filepath.FromSlash(secretAllowlistPath))
	if err := os.MkdirAll(filepath.Dir(allowlist), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(allowlist, []byte("{\"schema_version\":1,\"entries\":[]}\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "binary.bin"), []byte{'A', 0, 'B'}, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "generated.go"), []byte("// Code generated by test; DO NOT EDIT.\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(root, "target.txt")
	if err := os.WriteFile(target, []byte("safe\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(target, filepath.Join(root, "link.txt")); err != nil {
		t.Skipf("symlink unavailable: %v", err)
	}
	changes := filepath.Join(root, "changes.txt")
	if err := os.WriteFile(changes, []byte("missing.txt\nbinary.bin\ngenerated.go\nlink.txt\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	summary, err := runSecretScan(root, changes, false)
	if err != nil {
		t.Fatal(err)
	}
	if summary.SkippedDeleted != 1 || summary.SkippedBinary != 1 || summary.SkippedGenerated != 1 || summary.SkippedSymlink != 1 {
		t.Fatalf("unexpected skip accounting: %#v", summary)
	}
}

func TestSecretScannerFullScanUsesTrackedFiles(t *testing.T) {
	root := t.TempDir()
	runTestGit(t, root, "init")
	runTestGit(t, root, "config", "user.name", "CMDR Test")
	runTestGit(t, root, "config", "user.email", "cmdr-test@example.invalid")
	if err := os.MkdirAll(filepath.Join(root, "engineering", "security"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, filepath.FromSlash(secretAllowlistPath)), []byte("{\"schema_version\":1,\"entries\":[]}\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "safe.txt"), []byte("safe\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	runTestGit(t, root, "add", ".")
	runTestGit(t, root, "commit", "-m", "tracked")
	if err := os.WriteFile(filepath.Join(root, "untracked.txt"), []byte("ghp_"+strings.Repeat("C", 36)), 0o600); err != nil {
		t.Fatal(err)
	}
	summary, err := runSecretScan(root, "", true)
	if err != nil {
		t.Fatal(err)
	}
	if summary.Mode != "full" || summary.FindingCount != 0 {
		t.Fatalf("unexpected full scan: %#v", summary)
	}
}
